<?php

namespace DoctrineORMModule\Proxy\__CG__\Classe\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Classe extends \Classe\Entity\Classe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'libele', 'numero', 'quantite', 'enseignees', 'classeEleve', 'evaluations'];
        }

        return ['__isInitialized__', 'id', 'libele', 'numero', 'quantite', 'enseignees', 'classeEleve', 'evaluations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Classe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibele()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibele', []);

        return parent::getLibele();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibele($libele)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibele', [$libele]);

        return parent::setLibele($libele);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantite', []);

        return parent::getQuantite();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantite($quantite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantite', [$quantite]);

        return parent::setQuantite($quantite);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnseignee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnseignee', []);

        return parent::getEnseignee();
    }

    /**
     * {@inheritDoc}
     */
    public function addEnseignees($enseignees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEnseignees', [$enseignees]);

        return parent::addEnseignees($enseignees);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEnseigneeAssociation($enseignees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEnseigneeAssociation', [$enseignees]);

        return parent::removeEnseigneeAssociation($enseignees);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasseEleve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasseEleve', []);

        return parent::getClasseEleve();
    }

    /**
     * {@inheritDoc}
     */
    public function addClasseEleve($classeEleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClasseEleve', [$classeEleve]);

        return parent::addClasseEleve($classeEleve);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClasseEleveAssociation($classeEleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClasseEleveAssociation', [$classeEleve]);

        return parent::removeClasseEleveAssociation($classeEleve);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluations', []);

        return parent::getEvaluations();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvaluations($evaluations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvaluations', [$evaluations]);

        return parent::addEvaluations($evaluations);
    }

}
