<?php
$this->headScript()->appendFile('/js/jquery.dataTables.min.js', 'text/javascript');
$this->headLink()->appendStylesheet('/css/SearchStyle.css'); 
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');
$this->headTitle('Softnote- Planifier les matieres');
$this->mainMenu()->setActiveItemId('configuration');
$this->pageBreadcrumbs()->setItems([
            'Accueil'=>$this->url('home'),
            'Affectation des matières'=>$this->url('enseignee'),
            ]);

?>

<h3>Affester des matières a une classe</h3>
<div class="row">
      <div class="col-md-8">
          <form id="configuration_matiere_form" action="#">
            <p>
                <label for="classe_select"> Classe: </label>
                <select name="classe_select" id="classe_select" onchange="jsclasse(this.value);">
                    <option value="choisir" >Choisir</option>
                    <?php
                    foreach ($classes as $classe):
                       echo '<option value="'.$classe->getId().'">'.$classe->getLibele().'</option>';
                    endforeach;
                    ?>
                </select>
                <label for="periode_select"> Periode: </label>
                <select name="periode_select" id="periode_select">
                    <?php
                    foreach ($periodeval as $periode):
                       echo '<option value="'.$periode->getId().'">'.$periode->getDescription().'</option>';
                    endforeach;
                    ?>
                </select>
            </p>
            <div id="div_classe_data_matiere">
                <table id="tbl_classe_data_matiere"class="table table-striped table-bordered">
                    <tr><th></th><th>Libellé</th><th>Rang</th><th>Coefficient</th></tr>
                  <tbody id='matiere_not_classe'>
                
                  </tbody>
            
                </table>
            </div>
            
      <div class="modal-footer" id='submit_parts'>
       <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       <button type="submit"  id="submitbutton" class="btn btn-primary" >Enregistrer</button>
      </div>
     </form>
          <div id="div_matieres_classes">
          <table id="matieres_classes"class="table table-striped table-bordered">
              <tr><th></th><th>Libellé</th><th>Rang</th><th>Coefficient</th></tr>
             <tbody id="matieres">
                 
             </tbody> 
          </table>   
          </div>
     <!--<?//= $this->paginationControl($entites,
                   // 'Sliding',
                   // 'entite/partial/paginator', 
                   // ['route' => 'entite']); ?>-->
 </div>
    
   
</div>

<script type="text/javascript">
$(document).ready(function() {
    $('#classe_da').DataTable();
} );


function jsclasse(value)
{ 
    
       var value = value;
       var id_periode = $('#periode_select').val();
        document.getElementById("tbl_classe_data_matiere").innerHTML = "";
        document.getElementById("matieres_classes").innerHTML = "";
     if(value > 0){
         
           $.ajax({
            url: '/enseignee/affichermatiereclassee',
            type: "POST",
            dataType:"json",
            data:{classe:value, periode:id_periode},
            success: function(data) {
                
                var e = $('<tr><th></th><th>Libellé</th><th>Rang</th><th>Coefficient</th></tr>');
                    $('#tbl_classe_data_matiere').html(''); 
                    $('#tbl_classe_data_matiere').append(e);
              
              for(i = 0; i < data[0].length; i++) { 
                  
                matiere_not_classe = data[0][i];
                var e = $('<tr><td id = "id"></td><td id = "libele"></td><td id = "rang"></td><td id = "coefficient"></td></tr>'); 
                 $('#id', e).html('<input type="checkbox"  name="checkmatiere[]" value="'+matiere_not_classe['id']+'"/>'); 
                 $('#libele', e).html("<a id='"+matiere_not_classe['id']+"' href='#'>"+matiere_not_classe['libele']+"</a>");
                 $('#rang', e).html(matiere_not_classe['rang']);
                 $('#coefficient', e).html('<input type="number" step=5 min=0 name="coefficient[]" value=""/>'); 
                $('#tbl_classe_data_matiere').append(e); 
               
            }
            var e = $('<tr><th></th><th>Libellé</th><th>Rang</th><th>Coefficient</th></tr>');
                    $('#matieres_classes').html(''); 
                    $('#matieres_classes').append(e);
            for(i = 0; i < data[1].length; i++) { 
                  
                matieres = data[1][i];
                var e = $('<tr><td id = "id"></td><td id = "libele"></td><td id = "rang"></td><td id = "coefficient"></td></tr>'); 
                $('#id', e).html("<a id='"+matieres['id_enseignee']+"' href='#' onclick='desaffecter(this.id);' >"+'Desaffecter'+"</a>"); 
                $('#libele', e).html("<a id='"+matieres['id_enseignee']+"' href='#'>"+matieres['libele']+"</a>");
                $('#rang', e).html(matieres['rang']); 
                $('#coefficient', e).html(matieres['coefficient']); 
                $('#matieres_classes').append(e); 
               
            }
            document.getElementById("classe_select").reset();
            },error : function(jqXHR, textStatus, errorThrown) { 
           alert('An error occurred... Look at the console (F12 or Ctrl+Shift+I, Console tab) for more information!');
            $('#resulte').html('<p>Status Code: '+jqXHR.status+'</p><p>ErrorThrown: ' + errorThrown + '</p><p>jqXHR.responseText:</p><div>'+jqXHR.responseText + '</div>');
            console.log('jqXHR:');
            console.log(jqXHR);
            console.log('textStatus:');
            console.log(textStatus);
            console.log('errorThrown:');
            console.log(errorThrown);
         }
          
        });
        
  }else{
     alert('Vous devez choisir la classe');
  }
     return false;
}

$('#submitbutton').on( 'click', function() {
          
           var postData = new Array();
           var nms= 0;
           var id_periode = $('#periode_select').val();
           var checks = document.getElementsByName("checkmatiere[]");
           var coef = document.getElementsByName("coefficient[]");
           var id_classe = $('#classe_select').val();
          
           for (var i=0; i < checks.length; i++) {
                 
                       if(checks[i].checked == 1 && coef[i].value != ""){
                           
                                nms++;
                           for (var y=0; y < nms; y++){
                               postData[y] = {
                               "id_matiere": checks[i].value,
                               "coef": coef[i].value,
                              
                              };
                             
                           }   
                      }
                 }
                
     if(postData.length > 0){
       $.ajax({
            url: '/enseignee/add',
            type: "POST",
            dataType:"json",
            data:{postData:postData, classe:id_classe, periode:id_periode},
            success: function(result) {
                   alert('Enregistrement reussi');
                  document.getElementById("configuration_matiere_form").reset();
               
            },error : function(jqXHR, textStatus, errorThrown) { 
           alert('An error occurred... Look at the console (F12 or Ctrl+Shift+I, Console tab) for more information!');
            $('#resulte').html('<p>Status Code: '+jqXHR.status+'</p><p>ErrorThrown: ' + errorThrown + '</p><p>jqXHR.responseText:</p><div>'+jqXHR.responseText + '</div>');
            console.log('jqXHR:');
            console.log(jqXHR);
            console.log('textStatus:');
            console.log(textStatus);
            console.log('errorThrown:');
            console.log(errorThrown);
         } 
       });
       }else{
       alert('Aucune affectation');
       }
      return false; 
});



function desaffecter(value){
    
    alert(value);
    
     $.ajax({
            url: '/enseignee/desaffecter',
            type: "POST",
            dataType:"json",
            data:{matiere:value},
            success: function(data) {
                
                alert('Reussi');
                
            },error : function(jqXHR, textStatus, errorThrown) { 
           alert('An error occurred... Look at the console (F12 or Ctrl+Shift+I, Console tab) for more information!');
            $('#resulte').html('<p>Status Code: '+jqXHR.status+'</p><p>ErrorThrown: ' + errorThrown + '</p><p>jqXHR.responseText:</p><div>'+jqXHR.responseText + '</div>');
            console.log('jqXHR:');
            console.log(jqXHR);
            console.log('textStatus:');
            console.log(textStatus);
            console.log('errorThrown:');
            console.log(errorThrown);
         }
        });
        
        //document.getElementById("classe_select").reset();
}

</script>



<style>
    
</style>
<html></html> 
<html></html> 
<html></html> 
<html></html> 