<?php
$this->headScript()->appendFile('/js/jquery.dataTables.min.js', 'text/javascript');
$this->headLink()->appendStylesheet('/css/SearchStyle.css'); 
$this->headLink()->appendStylesheet('/css/jquery.dataTables.min.css');
$this->headTitle('Softnote-Gestion des notes');
$this->mainMenu()->setActiveItemId('configuration');
$this->pageBreadcrumbs()->setItems([
            'Accueil'=>$this->url('home'),
            'Affectation des élèves'=>$this->url('classeeleve'),
            ]);

?>

<h3>Affectation des élèves</h3>

<div class="row">
    <div class="col-md-4">
       <div class="panel panel-default">
           <div class="row">
              <div class="col-md-6">
                <p>
                    <a class="btn btn-default" href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Affectation des élèves dans une classe
                    </a>
                    Annee Scolaire : <?= $this->escapeHtml($anneescolaire->getLibele()); ?> <input type="hidden" name="anneescolaire" id="anneescolaire"  value="<?= $this->escapeHtml($anneescolaire->getId()); ?>"/> 
                </p>
               
          <form id="affectation_eleve__form" action="">
             <table id="eleve_data"class="table table-striped table-bordered">
    
                 <thead>
                    <tr>
                    <th></th>
                    <th>Choisir</th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Statut</th>
                    <th>Actions</th>
                   </tr>
                 </thead>

                    <tbody>
                    <?php foreach ($eleves as $eleve): ?>

                    <tr>

                        <td width='30px'>
                            <a class="" href="<?= $this->url('eleve',['action'=>'view', 'id'=>$eleve->getId()]); ?>">
                                <span class="glyphicon glyphicon-search" ></span>
                            </a>    
                        </td>
                         <td width='50px'>
                             <input type="checkbox" name="eleves_check[]" value="<?= $this->escapeHtml($eleve->getId()); ?>"/>
                        </td>
                        <td>
                            <?= $this->escapeHtml($eleve->getNomEleve()); ?></a> 
                        </td> 
                        <td>
                            <?= $this->escapeHtml($eleve->getPrenomEleve()); ?></a> 
                        </td>
                        <td>
                            <?= $this->escapeHtml($eleve->getStatusAsString()); ?></a> 
                        </td>
                        <td>
                          <nobr>  
                              <a class="bt-supprimer" href="" onclick="js_enregistrer(<?= $this->escapeHtml($eleve->getId()); ?>);">
                                 <span class="glyphicon glyphicon-send"></span> Affecter
                             </a>
                          </nobr>
                        </td>
                    </tr>

                    <?php endforeach; ?>  
                     </tbody>
            </table>
              
                 <div class="modal-footer" id='submit_parts'>
                    <button type="button" class="glyphicon glyphicon-refresh" data-dismiss="modal"></button>
                    <button type="submit"  id="submitbutton" class="btn btn-primary" >Enregistrer</button>
                 </div>
              
           </form>
          </div> 
       </div>
   </div>
 </div>
    
    
    <div class="col-md-4">
       <div class="panel panel-default">
                      
            <div class="row">
             <div class="col-md-6">
                 
               <p>
                    <a class="btn btn-default" href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Veuiller choisir la classe
                    </a>
                    <label for="classe_select"> Classe: </label>
                    <select name="classe_select" id="classe_select" onchange="jsclasseeleve(this.value);">
                        <option value="0" >Choisir</option>
                        <?php
                        foreach ($classes as $classe):
                           echo '<option value="'.$classe->getId().'">'.$classe->getLibele().'</option>';
                        endforeach;
                        ?>
                    </select>
               </p>
            <div id="div_tbl_eleves_classe">
             
           </div>
         </div> 
        </div>
   </div>
 </div>
     
</div>

<script type="text/javascript">
$(document).ready(function() {
    $('#eleve_data').DataTable();
} );
function jquerytable(id_table, class_table){
$(document).ready(function() {
    $('#'+id_table+'').DataTable();
    $("#div_tbl_eleves_classe table").addClass(''+class_table+'');
} );
}


function jsclasseeleve(value)
{ 
     var value = value;
      //document.getElementById("eleves_data").innerHTML = "";
     if(value > 0){
           $.ajax({
            url: '/classeeleve/afficherEleves',
            type: "POST",
            dataType:"json",
            data:{classe:value},
            success: function(data) {
                
              var e = $('<table id="eleves_data" class:"table table-striped table-bordered"><thead><tr><th></th><th>Nom</th><th>Prénom</th></tr></thead><tbody id="book_eleves"></tbody></table>');
              $('#div_tbl_eleves_classe').html(''); 
              $('#div_tbl_eleves_classe').append(e);
              
              for(i = 0; i < data.length; i++) {    
                book_eleves = data[i];
                var e = $('<tr><td id = "id"></td><td id = "nom"></td><td id = "prenom"></td></tr>'); 
                $('#id', e).html("<a id='"+book_eleves['id_eleve']+"' href='#'>"+book_eleves['id_eleve']+"</a>"); 
                $('#nom', e).html("<a id='"+book_eleves['nom']+"' href=''>"+book_eleves['nom']+"</a>");
                $('#prenom', e).html(book_eleves['prenom']);
                 
                $('#eleves_data').append(e); 
               
            }
            jquerytable('eleves_data', 'table table-striped table-bordered');
            },error : function(jqXHR, textStatus, errorThrown) { 
           alert('An error occurred... Look at the console (F12 or Ctrl+Shift+I, Console tab) for more information!');
            $('#resulte').html('<p>Status Code: '+jqXHR.status+'</p><p>ErrorThrown: ' + errorThrown + '</p><p>jqXHR.responseText:</p><div>'+jqXHR.responseText + '</div>');
            console.log('jqXHR:');
            console.log(jqXHR);
            console.log('textStatus:');
            console.log(textStatus);
            console.log('errorThrown:');
            console.log(errorThrown);
         }
        });
        
  }else{
     alert('Vous devez choisir la classe');
  }
     return false;
}


function js_enregistrer(value)
{ 
           var id_eleve = value;
           var id_classe = $('#classe_select').val();
           var id_anneescolaire = $('#anneescolaire').val();
      
    if(id_classe != 'choisir'){
       $.ajax({
            url: '/classeeleve/affecterEleve',
            type: "POST",
            dataType:"json",
            data:{eleve:id_eleve, classe:id_classe, anneescolaire:id_anneescolaire},
            success: function(result) {
                  alert(result['messagederetour']);
                  //document.getElementById("configuration_matiere_form").reset();
               
            },error : function(jqXHR, textStatus, errorThrown) { 
           alert('An error occurred... Look at the console (F12 or Ctrl+Shift+I, Console tab) for more information!');
            $('#resulte').html('<p>Status Code: '+jqXHR.status+'</p><p>ErrorThrown: ' + errorThrown + '</p><p>jqXHR.responseText:</p><div>'+jqXHR.responseText + '</div>');
            console.log('jqXHR:');
            console.log(jqXHR);
            console.log('textStatus:');
            console.log(textStatus);
            console.log('errorThrown:');
            console.log(errorThrown);
         } 
       });
       }else{
       alert('Vous devez choisir une classe ');
       }
  
  return false;
}

$('#submitbutton').on( 'click', function() {
    
     var eleves = new Array();
     var eleves_check = document.getElementsByName("eleves_check[]");
     var id_classe = $('#classe_select').val();
     var nms= 0;
        for (var i=0; i < eleves_check.length; i++) {
                 
                       if(eleves_check[i].checked == 1){
                           
                                nms++;
                           for (var y=0; y < nms; y++){
                               eleves[y] = {
                               "id_eleve": eleves_check[i].value,                              
                              };
                             
                           }   
                      }
                 }
    
       if(id_classe != 0 && eleves.length > 0){
           
       $.ajax({
            url: '/classeeleve/affecterEleves',
            type: "POST",
            dataType:"json",
            data:{eleves:eleves, classe:id_classe},
            success: function(result) {
                  alert(result['messagederetour']);
                  //document.getElementById("configuration_matiere_form").reset();
            },error : function(jqXHR, textStatus, errorThrown) { 
           alert('An error occurred... Look at the console (F12 or Ctrl+Shift+I, Console tab) for more information!');
            $('#resulte').html('<p>Status Code: '+jqXHR.status+'</p><p>ErrorThrown: ' + errorThrown + '</p><p>jqXHR.responseText:</p><div>'+jqXHR.responseText + '</div>');
            console.log('jqXHR:');
            console.log(jqXHR);
            console.log('textStatus:');
            console.log(textStatus);
            console.log('errorThrown:');
            console.log(errorThrown);
         } 
       });
       }else{
       alert('Vous devez choisir une classe ');
       }
   return false;
});

</script>
<style>
    .col-md-8b{width: 40% !important;
    }
    .panel-body{padding: 2px !important;
    }
    .container{
        padding-right: 0px;
        padding-left: 0px;
        margin-right: auto;
        margin-left: auto;
    }
    .h1, .h2, .h3, h1, h2, h3{
        margin-top: 0px !important;
    }
    .bt-supprimer{
        color: #ff0000;
    }
   
    .col-md-6{
        
        width: 100%!important;
    }
    .col-md-4 {
    width: 50%;
}
    
</style>
<html></html> 
<html></html> 
<html></html> 
<html></html> 